### ISSUE TITLE
Basket Data

### ISSUE THREAD

**Issue by DrewNF** [Dreamvention/d_quickcheckout#29]
Hi guys, 
thanks for your great work, really works well. 
I have one question regarding this modification. I am working with an OpenCart Shop and trying to access the Basket Data.
Usually I am able to write JavaScript code that can access the basket data in catalog/view/theme/*/template/checkout/cart.tpl . However I am aware that this modification changes the structure of the basket. 
I see that you have an updateState method, which I assume is used to update the state of the basket, without the need to reload the page. So to me it seems to me as if no *.tpl file is used.
Where do you think would be the best to put JavaScript code that can access the basket data? 

Thanks so much,
Andrea

**Comment by dmitriyzhuk** [comment]
Hi

you can just call in your javascript this method 

qc.updateState(['session', 'cart', 'products'], { ... });

this will update the cart everywhere it is needed.
